// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPaA-FtfuRQYg_BxrPx3Eez7pLqnRYuzQ',
    appId: '1:794052151379:web:df7c66813abff54ef31ea6',
    messagingSenderId: '794052151379',
    projectId: 'delta-project-d65f9',
    authDomain: 'delta-project-d65f9.firebaseapp.com',
    storageBucket: 'delta-project-d65f9.appspot.com',
    measurementId: 'G-CFFY1YSQ7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX--n2GGVVpHxD9Okfp9wDoP5vK1m74Gc',
    appId: '1:794052151379:android:78cf0851e35620cbf31ea6',
    messagingSenderId: '794052151379',
    projectId: 'delta-project-d65f9',
    storageBucket: 'delta-project-d65f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZhYK5cF78sMUZbyhI6_bQYBsasQsADrI',
    appId: '1:794052151379:ios:d4579b9521041200f31ea6',
    messagingSenderId: '794052151379',
    projectId: 'delta-project-d65f9',
    storageBucket: 'delta-project-d65f9.appspot.com',
    iosClientId: '794052151379-4e56lftjfbjbf8qritia8be0lotdo6gs.apps.googleusercontent.com',
    iosBundleId: 'com.example.delta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZhYK5cF78sMUZbyhI6_bQYBsasQsADrI',
    appId: '1:794052151379:ios:d4579b9521041200f31ea6',
    messagingSenderId: '794052151379',
    projectId: 'delta-project-d65f9',
    storageBucket: 'delta-project-d65f9.appspot.com',
    iosClientId: '794052151379-4e56lftjfbjbf8qritia8be0lotdo6gs.apps.googleusercontent.com',
    iosBundleId: 'com.example.delta',
  );
}
